version: "3.9"
services:
  golang:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./:/go/src/main
    ports:
      - 8080:8080
  #database:
  #      image: mysql/mysql-server:8.0
  #      volumes:
  #          - ./docker-data/mysql:/var/lib/mysql
  #      ports:
  #          - 3306:3306
  #      environment:
  #          MYSQL_DATABASE: golang
  #          MYSQL_ROOT_PASSWORD: secret
  #          MYSQL_PASSWORD: secret2
  #          MYSQL_USER: forge